name: Axe Watcher

on: push

jobs:
  axe-dev-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dequelabs/axe-devhub-action@v1
        with:
          api_key: ${{ secrets.AXE_API_KEY }}
