name: E2E on Chrome

on: push

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: pnpm run build
          start: pnpm run start
          browser: chrome
          headed: true
          wait-on: "http://localhost:3000"
        env:
          AXE_API_KEY: ${{ secrets.AXE_API_KEY }}
  axe-dev-hub:
    runs-on: ubuntu-latest
    needs: cypress
    steps:
      - uses: actions/checkout@v3
      - uses: dequelabs/axe-devhub-action@v1
        with:
          api_key: ${{ secrets.AXE_API_KEY }}
